### PR TITLE
[Issue #235 fix] Fixed scroll on reordering activities

### LINKED ISSUE #235: Activity list doesn't scroll while reordering, causes multiple server calls.
The activity list in the Dashboard does not scroll up/down while reordering activities. This leads to multiple drag-and-drops to reorder single activity and each drop causes a POST request to update the list on the server.
Also, there is an unnecessary POST request even when the list order hasn't changed.

dragScrollIssue

### PR DESCRIPTION
**Pull request by dhruvmisra**
Fixes #235 
Removed the jquery-sortable dependency and handling the sorting and drag-and-drops using the already existing jquery-ui dependency. Calling the updateActivities() function only when the list has been updated reducing the unnecessary server calls. Also added a smooth animation while reordering.

dragScrollFix

### CODE REVIEW

**Comment by NikhilM98** [comment]
This will cause the List Chart view to crash. Fix it there too:
Screenshot from 2020-03-09 11-34-36

**Comment by dhruvmisra** [comment]
@NikhilM98 Fixed the problem in my latest commit. Please review.

**Comment by NikhilM98** [comment]
Can you run `npm run lint` and fix the indentation.

**Comment by dhruvmisra** [comment]
@NikhilM98 Something weird, the file had correct indentation on my IDE but messed some of it after the push. Fixed it nevertheless.

**Comment by NikhilM98** [comment]
> Removed the jquery-sortable dependency

- The dependency is still present (`dashboard/public/js/jquery-sortable.js`).
- Can you add `dashboard/public/js/jquery.ui.sortable-animation.js` to `.eslintignore` and remove the deleted files from there too.

**Comment by dhruvmisra** [comment]
@NikhilM98 Made the required changes.

**Comment by NikhilM98** [comment]
There are too many unnecessary changes in `main.js`. Can you limit the changes to your code (minimum required).

**Comment by dhruvmisra** [comment]
That was the result of linting the file. All the indentations and spaces were reset which are showing up as new changes on git. The only changes I made were in `initDragDrop()` and `initChartDragDrop()`.

**Comment by NikhilM98** [comment]
Yes, spaces were added in the whole file and those changes are unnecessary.

**Comment by dhruvmisra** [comment]
@NikhilM98 Removed the unnecessary spaces.

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
