### PR TITLE
Ansible package for easy deployment on GCP

### PR DESCRIPTION
**Pull request by ksraj123**
Fixes Issue #256 

This ansible package simplifies the current deployment method for deploying sugarizer-server on vm instances on google compute engine.
It creates and configures a vm instance and firewall, installs dependencies and deploys sugarizer-server onto the vm instance, it also prints the external IP of the vm instance where the deployment can be accessed.
 
This could be tested with steps described in `ansible/docs/ansible-deployToGcp.md` of this PR.

### CODE REVIEW

**Comment by ksraj123** [comment]
@NikhilM98 Thanks for reviewing. I have made the suggested changes. Deprecated module `gce` has been replaced with `gcp_compute_instance`

Yes, ansible/deploy-to-gcp does not have any direct dependence upon Sugarizer Server Code that is why only this specific directory is downloaded to the user's local machine by steps mentioned in ansible/docs as we do not want the user to unnecessarily download the entire repository.

`get_start_script` uses code from github as this script is being executed in our vm instance on GCP not the user's local machine where the code might already be present.

Ansible packages for other deployments methods too can be created in future and they can all be inside the ansible folder, I think it will promote gradual transition to using ansible as the preferred way to setup sugarizer-server specially by non-developers. However separating it into another repository is also a good option.

Requesting suggestions @llaske

**Comment by NikhilM98** [comment]
> `get_start_script` uses code from github as this script is being executed in our vm instance on GCP not the user's local machine where the code might already be present.

Have you tested providing `startup-script` directly instead of `startup-script-url`?
Reference: [link](https://cloud.google.com/compute/docs/startupscript)

**Comment by ksraj123** [comment]
@NikhilM98 Thanks for suggestion. `startup-script` was not used initially as providing path to script file as described in the reference link did not work, maybe because I could not seem to find `gcp_compute_instance` counterpart of `--metadata-from-file` flag of `gcloud`.  We could have installed google cloud sdk on the local machine of the user and used the gcloud command as in the reference link but its relatively heavy weight or provide the content directly but it would clutter our playbook. However another work around is used in which the script is defined in a yaml file and variables from that file is included in our playbook. This approach also ensures that user does not execute the startup script which is meant to be executed on the vm instance on his local machine.

**Comment by NikhilM98** [comment]
It looks better now. The reference link was added to point out that we can use `startup-script` as a metadata key instead of `startup-script-url` to provide the startup instructions.

Btw the file `4.png` is uploaded but not used.

**Comment by ksraj123** [comment]
@NikhilM98 the unused image `4.png` has been removed.

**Comment by llaske** [comment]
@mikklfr could you review this and see if it could be helpful for Sugarizer School Portal project.

**Comment by mikklfr** [comment]
Hi!
This is nice, this Ansible recipe will allow to easily create and fill up an instance.

That's not linked with the school project technically as this approach is not about sharing a pool of resources for many schools but about setting up a single deploy.

But that is nice and could simplify deployments for some.

**Comment by llaske** [comment]
Okay.

@ksraj123 could you:
- Reduce images size, currently 1920x880, should be near 800x400
- Could you put all documents into `docs` directory instead of the `ansible/docs` directory
- Could you reference - or even include - your documentation into existing GCP documentation. May be you could describe it as an alternative to manual install
- Use relative path `llaske/sugarizer-server/dev` instead of `ksraj123/sugarizer-server/patch-1`

**Comment by ksraj123** [comment]
@llaske Suggested changes made, please review.

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
