### PR TITLE
Update ejs version

### PR DESCRIPTION
**Pull request by SomtochiAma**
This upgrades the ejs version from the package.json and adds some minor changes to the views

### CODE REVIEW

**Comment by ashish0910** [comment]
@SomtochiAma please make pr to dev branch not master .

**Comment by ahmedkrmn** [comment]
Just as @ashish0910 told you. Make your PR to the `dev` branch, and also when creating your new fix branch, make sure that the `dev` branch was checked out.

**Comment by SomtochiAma** [comment]
Thank you for your response. I appreciate it a lot. I will work on them
today.  How can I change the pr from master to the dev branch.

Also,  I was thinking if I should still write a proposal for GSoC. My
chances of getting in are very slim and I don't know if I should just leave
it, work on my skills then apply next year or apply this year.

**Comment by ashish0910** [comment]
@SomtochiAma looks like @tarunsinghal92 already did the change of branch from master to dev .

**Comment by tarunsinghal92** [comment]
old branch, too many conflict. closing!

**Pull request closed without merging**
