### PR TITLE
[WIP] Bash script for setup

### PR DESCRIPTION
**Pull request by NikhilM98**
I'm working on writing a bash script for project setup. It includes
- Testing for Git
- Testing for Node
- Testing for NPM
- Installing Sugarizer-Server npm modules
- Cloning Sugarizer, npm installing modules
- Creating config (`sugarizer.ini`)
- Creating admin

Not added features for testing DB. I'm assuming that DB is already running.
Not added features for installing Git, Node and NPM

@llaske @tarunsinghal92 can you please review the code for issues and features needed.

### CODE REVIEW

**Comment by ashish0910** [comment]
@NikhilM98 I was already working on this !! (although i did not open pr with WIP tag). You have already opened almost 15 pr in 4 days span. Now doing such things affects competition in a negative manner and definitely reduces quality of work . Open source is not development by single person . Please have a look at the pr's you have already opened and let others also contribute . There is no point of doing open source development with this kind of approach . @tarunsinghal92 @llaske

**Comment by NikhilM98** [comment]
@ashish0910 Contributing open source is not about competition. Contributing open source helps in improving the quality of your existing skills, find mentors and teach others, learn the skills to work in an organization. Lastly, it's about the feeling when your code gets merged and it makes you happy to know that thousands of people use your code in their day to day life.

If you're working on something you, need to let the other contributors know that you're working on that issue. I have no way of knowing that someone is already working on that issue. Speaking about reducing the quality of code. I don't think so. I've spent several hours researching and implementing the code I've written. It's not good to judge the quality of code of a fellow contributor with shallow reasoning. To solve this issue I spent 4+ hours of planning, studying bash and implementing. If your feedback is not constructive, it's not helpful.

About the [WIP] PRs. I've 4 [WIP] PRs including this one. I've opened those PRs since I've reached a checkpoint and I need suggestion from the community for moving ahead. Those PRs can be merged, they're tested, but I'm not sure about the implementation so I decided to let the maintainers know that they're no ready.

It's not like there is nothing left to do in the project. You can go through the project as a tester, if you find some bug/improvement you can work on that. There are a huge scope of improvement for this project. I've been testing the project for bugs/improvements. I've some issues in mind that I was about to work on. If you could not find any bugs, I'll be glad to show you some bugs I found.

Happy Coding!

**Comment by llaske** [comment]
Please @ashish0910 and @NikhilM98, read [code of conduct](https://github.com/llaske/sugarizer/blob/master/CODE_OF_CONDUCT.md) and [contributing](https://github.com/llaske/sugarizer/blob/master/CONTRIBUTING.md).

Plus I don't think we need this sort of script. Docker is the preferred way to run Sugarizer Server and people who want to install Sugarizer Server themselves don't need a step by step script.

**Comment by NikhilM98** [comment]
@llaske It was mentioned [here](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2019.md#improve-sugarizer-server-dashboard) to add scripting and that to start implementing suggested improvements.

I personally think that there should be an easy way for non programmers (Like teachers/School Administrators) to set-up the server. Also, since the the school computers can be old, I deciced not to use docker and follow old-school installation to maximise efficiency.

**Comment by llaske** [comment]
For non programmers, we're providing [Sugarizer SchoolBox](https://github.com/llaske/sugarizer-school-box). It can be installed on a RaspberryPI without any knowledge.
Not sure old computers is a problem with docker, Sugarizer SchoolBox itself use docker.

Regarding scripting, Im' thinking more to script to initialize database content.

**Comment by NikhilM98** [comment]
@llaske I see, there are already well-written script scripts to do just that on Sugarizer SchoolBox.
There's already a script to create admins. The script for admin seems sufficient. Thanks to MongoDB, Sugarizer-Server can be used without much database seeding.
Can you explain more about the script that's needed?

**Pull request closed without merging**
