### PR TITLE
Use single instance of db connection

### PR DESCRIPTION
**Pull request by NikhilM98**
`client.connect` was not handled in the `api/controller`. If the database is not running, the application should exit with an error code and return that application cannot be connected with DB.

### CODE REVIEW

**Comment by NikhilM98** [comment]
Before handling else:
screenshot from 2019-03-04 02-21-09

After handling else:
screenshot from 2019-03-04 01-07-32

Now its returning that it cannot connect with the DB and exits the process with -1 error code.

**Comment by NikhilM98** [comment]
Yes, I was also wondering why DB connections were defined redundantly in each `api/controller`. It was establising multiple connections with the DB. I was new to the repository back then.
Now when I think about it. I can think of two things:
- The function `waitConnection` can be modified to call the callback with `client` as an argument (Without calling `client.close()`).The client would then be passed down to `./api/route` and then further passed down to different routes (Using `.init`).
- We can also export the `client` from `wait4db.js` and it can be imported and used by the `api/controller` for DB queries. 
https://github.com/llaske/sugarizer-server/blob/7d54cf1239929513abcd533362a5e68663870c60/config/wait4db.js#L14-L37

@tarunsinghal92 which approach do you think we should take?

**Comment by tarunsinghal92** [comment]
> Yes, I was also wondering why DB connections were defined redundantly in each `api/controller`. It was establising multiple connections with the DB. I was new to the repository back then.
> Now when I think about it. I can think of two things:
> 
> * The function `waitConnection` can be modified to call the callback with `client` as an argument (Without calling `client.close()`).The client would then be passed down to `./api/route` and then further passed down to different routes (Using `.init`).
> * We can also export the `client` from `wait4db.js` and it can be imported and used by the `api/controller` for DB queries.
>   
>     
>       
>         [sugarizer-server/config/wait4db.js](https://github.com/llaske/sugarizer-server/blob/7d54cf1239929513abcd533362a5e68663870c60/config/wait4db.js#L14-L37)
>       
>       
>           Lines 14 to 37
>         in
>         [7d54cf1](/llaske/sugarizer-server/commit/7d54cf1239929513abcd533362a5e68663870c60)
>       
>       
>       
>       
>   
>           
>             
>              exports.waitConnection = function(settings, callback) { 
>           
>   
>           
>             
>              	var waitTime = settings.database.waitdb; 
>           
>   
>           
>             
>              	if (waitTime) { 
>           
>   
>           
>             
>              		var timer = setInterval(function() { 
>           
>   
>           
>             
>              			server = new Server(settings.database.server, settings.database.port, {auto_reconnect: false}); 
>           
>   
>           
>             
>              			db = new Db(settings.database.name, server, { 
>           
>   
>           
>             
>              				w: 1 
>           
>   
>           
>             
>              			}); 
>           
>   
>           
>             
>               
>           
>   
>           
>             
>              			// Open the db 
>           
>   
>           
>             
>              			db.open(function(err, db) { 
>           
>   
>           
>             
>              				if (!err) { 
>           
>   
>           
>             
>              					clearInterval(timer); 
>           
>   
>           
>             
>              					db.close(); 
>           
>   
>           
>             
>              					callback(); 
>           
>   
>           
>             
>              				} else { 
>           
>   
>           
>             
>              					console.log("Waiting for DB..."); 
>           
>   
>           
>             
>              				} 
>           
>   
>           
>             
>              			}); 
>           
>   
>           
>             
>              		}, waitTime*1000); 
>           
>   
>           
>             
>              	} else { 
>           
>   
>           
>             
>              		callback(); 
>           
>   
>           
>             
>              	} 
>           
>   
>           
>             
>              }
> 
> @tarunsinghal92 which approach do you think we should take?

make the db connection and pass it to controller while initializing them

**Comment by NikhilM98** [comment]
Passed the tests.
Screenshot from 2019-03-11 00-59-36

**Comment by NikhilM98** [comment]
@llaske @tarunsinghal92 can you review this PR. The objective of this PR is to reduce the number of active mongodb instances the server is using.

**Comment by NikhilM98** [comment]
@tarunsinghal92 rebased with upstream dev

**Pull request merged**
