### PR TITLE
Final workflow

### PR DESCRIPTION
**Pull request by parteekcoder**
issue #293

### CODE REVIEW

**Comment by NikhilM98** [comment]
The destination should be `dev`, not `master`.

**Review by NikhilM98 — APPROVED** [review]
These changes look good to me.

@llaske do you have any thoughts?

**Comment by parteekcoder** [comment]
@NikhilM98 now you can review, I understand that merging a lots of commit for a PR causes problem for you in the future that's I separated this

**Comment by NikhilM98** [comment]
@parteekcoder great, thanks!

**Comment by parteekcoder** [comment]
> @parteekcoder great, thanks!

Also to you @NikhilM98 for guiding and helping where I needed

**Comment by parteekcoder** [comment]
hey @llaske please review this PR

**Comment by llaske** [comment]
Thanks @parteekcoder . Good job.

**Comment by parteekcoder** [comment]
Thanks @llaske @NikhilM98 I would like to contribute more

**Pull request merged**
