### PR TITLE
Made a few changes in the readme file

### PR DESCRIPTION
**Pull request by annu12340**

### CODE REVIEW

**Comment by llaske** [comment]
Thanks for change but please you should do your PR on the dev branch.

**Comment by annu12340** [comment]
Hi, I am a beginner to Github. 
You meant I got to 'git checkout -b change_doc ' and then send the pr, right?

**Comment by llaske** [comment]
No I mean that you should update the README file on the dev branch.
If you've done your PR using Github, close it and do another using llaske:dev branch instead of llaske:master branch.

**Comment by annu12340** [comment]
Ok
Thank you

**Pull request closed without merging**
