### PR TITLE
localisation for translating language

### PR DESCRIPTION
**Pull request by ashish0910**
Currently the select box shows the available languages in English only . This PR added localisation for that select box .
Current Behaviour:
Screenshot 2019-03-25 at 7 55 36 PM

Expected Behaviour:
Screenshot 2019-03-25 at 7 51 58 PM

### CODE REVIEW

**Comment by ashish0910** [comment]
@NikhilM98 Thanks for your suggestion , as long as project is improved I don't think there should be any problem in this also I did not see any pr for this change in this project so I opened it . 
Regarding the taking local language of browser , I will do the changes accordingly .

**Comment by NikhilM98** [comment]
@ashish0910 
- Use of `english-nav`, `hindi-nav`, `spanish-nav` and `french-nav` in locales looks redundant when compared to #145

- I don't understand what you mean by:
> Regarding the taking local language of browser 
 
But implementing double translation while fixing English names doesn't seem a good idea.

It'll look better if you use double translation as suggested in Sugarizer [#293](https://github.com/llaske/sugarizer/pull/293).

**Comment by YJDave** [comment]
@ashish0910 The way translation are fixed in #293 is to change it to "language name without any translation + (language name translated to local language)".

**Comment by ashish0910** [comment]
If local language in English:

Screenshot 2019-03-26 at 8 19 06 AM

If local language is French:

Screenshot 2019-03-26 at 8 31 12 AM

If local language is Hindi:

Screenshot 2019-03-26 at 8 19 25 AM

In `()` it shows language name translated to local language and without `()` it shows original language name without being translated to any other language.

**Comment by ashish0910** [comment]
@tarunsinghal92 resolved conflicts

**Comment by llaske** [comment]
Nice but it require to increase size of language selection field because the value is not fully visible now.

Capture d’écran de 2019-04-10 17-16-01

Thanks to resolve new conflicts too.

**Comment by ashish0910** [comment]
@llaske done the fixes

Screenshot 2019-04-10 at 9 26 45 PM

**Comment by ashish0910** [comment]
@llaske can you please review this pr

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
