### PR TITLE
Issue fix #294: text align changed on Language selector

### LINKED ISSUE #294: padding from left required in language selection menu list
Screenshot below :arrow_down: 
Can i fix this selection menu? @llaske  
#### i wrote the code and fix this thing .! it is good to make a pull request?

e4603fb2-d4d0-48b6-a833-684de82d1237
?

### PR DESCRIPTION
**Pull request by bdbose**
A same css change on the language selector 
image

### CODE REVIEW

**Comment by NikhilM98** [comment]
Can you add test screenshots with different window sizes, including mobile view?

**Comment by bdbose** [comment]
@NikhilM98  
Tablet
image

Mobile
image

Window(1024x973)
image

**Comment by NikhilM98** [comment]
Looks good! Can you change the destination of the PR from master to dev?

**Comment by bdbose** [comment]
@NikhilM98  changed to dev 👍🏼

**Review by NikhilM98 — APPROVED** [review]

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/commit/7e1cec20a4ece69230cd703bd8e1811bfa33598c

**Pull request merged**
