### PR TITLE
Add sorting functionality

### LINKED ISSUE #78: Sort tables in Users/Classrooms by clicking on the column header
This is an enhancement feature that I think would be very handy if added to the project.
The admin can click on the header he/she wants to sort the table by whether it's students table, the admins table or the classrooms table.

Here are two Gifs demonstrating the functionality:
**Users (Students/Admins):**

Users2

**Classrooms:**

Classrooms

**PR  #79  implements this desired functionality.**

_Note: The cursor icon not changing when hovering over the header of the specific column is a UI issue that is also present with items on the sidebar._

### PR DESCRIPTION
**Pull request by ahmedkrmn**
Sort by clicking on the desired column header in the table of both the Users and Classrooms tabs.

Fixes #78

### CODE REVIEW

**Comment by ashish0910** [comment]
@ahmedkrmn I am already working on this and have already opened a pr #77 and issue #50  . Please read contribution guidelines [here](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#contributing) .

**Comment by ahmedkrmn** [comment]
@ashish0910 I already did. I saw you've been working on this issue since a week ago and I was waiting for a final PR from you which you have recently pushed here #77.
I saw you used the API requests to reload the entire table again in your PR. The way I implemented the functionality is totally different than the way you did, it's all at the client side with no need to reload the content again.
Thanks.

**Comment by ashish0910** [comment]
Yes I know your implementation is different from mine but I was waiting for feedback from the maintainer and a pr is not final until it is merged or closed . You can add more changes as per the feedback of maintainers . @ahmedkrmn you can also recommend me but it does not mean you can open a different pr for it . 
There is a huge scope of improvement for this project , You can work on some other issues if you want.
Happy coding .

**Comment by ahmedkrmn** [comment]
@ahmedkrmn I thought about it and @ashish0910 was working on it as well, but I believe that sorting the tables on the client side is more optimal since we won't need to re-load the entire content and fetch the data once again. 
Please provide your insights on why we need it to be carried out by the server.

**Comment by llaske** [comment]
Clearly, sorting should be done on the server side. So the @ashish0910 proposal is better thought the UI should be change like @tarunsinghal92 mention [here](https://github.com/llaske/sugarizer-server/pull/77#pullrequestreview-212607245).

**Comment by ahmedkrmn** [comment]
@llaske Yeah, realized we're using pagination making sorting on the server required. Thanks.

**Pull request closed without merging**
