### PR TITLE
Create BuildAndTest.yml

### PR DESCRIPTION
**Pull request by parteekcoder**
Intiative of creating Automation and testing using github workflow

issue #293 

@llaske I implemented github workflow, Any suggestions from you will be admired

### CODE REVIEW

**Comment by llaske** [comment]
@parteekcoder did you test it on your side?
It can't work. Running test require not only a node environment but also a MongoDB database.

**Comment by parteekcoder** [comment]
> @parteekcoder did you test it on your side? It can't work. Running test require not only a node environment but also a MongoDB database.

yeah will update it

**Comment by parteekcoder** [comment]
@llaske can we use something test database and use the data from it for testing ,

as using original database or the testing is not so good, What do you think?

**Comment by parteekcoder** [comment]
hey @llaske can we use something like this we can connect to remote mongodb database having testing data
We can store the mongodb uri in the github secrets

@llaske is that sounds good to you 

If you want it to do in some other way please tell me , so that I can implement that

**Comment by llaske** [comment]
No. The idea is to create a mongodb in the same github action

**Comment by parteekcoder** [comment]
> No. The idea is to create a mongodb in the same github action

but then we have to populate test data in it , right?

**Comment by llaske** [comment]
No. Have a look on tests, they create their own items.

**Comment by parteekcoder** [comment]
ok then it is easy I will update this PR soon

**Comment by NikhilM98** [comment]
@parteekcoder can you set up these Github Actions in your repository fork for testing? Since the original repository is being used by other contributors, testing this feature here can lead to confusion. It may be better to test and develop this feature on your fork, and once the feature is stable share the instructions about setting it up on this repository.

**Comment by NikhilM98** [comment]
@parteekcoder can you also add a [WIP] tag in the name of your PR so that it's clear that they are not ready?
> [WIP] Create BuildAndTest.yml

**Comment by parteekcoder** [comment]
I don't have access to add labels

**Comment by parteekcoder** [comment]
> @parteekcoder can you set up these Github Actions in your repository fork for testing? Since the original repository is being used by other contributors, testing this feature here can lead to confusion. It may be better to test and develop this feature on your fork, and once the feature is stable share the instructions about setting it up on this repository.

@NikhilM98 can you please tell me how `test` will run if they are present in another repository

**Comment by parteekcoder** [comment]
@NikhilM98 as running test on sugarizer-server it requires sugarizer repo , so first I also have to clone that repo, right ?

**Comment by NikhilM98** [comment]
You should be able to configure github actions in your fork: https://github.com/parteekcoder/sugarizer-server

**Comment by parteekcoder** [comment]
@NikhilM98 I am closing this PR , I created new one you can check that

**Pull request closed without merging**
