### PR TITLE
Remove text field from aggregate journal query

### LINKED ISSUE #208: Server crash when dashboard call with several thousand of entries
When the dashboard is run on a database with several thousand of entries, the graph not drawn and the server crash.

image

On the server side the error is:

```
<--- Last few GCs --->

[18304:0x3924b60]    41557 ms: Mark-sweep 1347.3 (1456.2) -> 1347.3 (1456.2) MB, 141.8 / 0.0 ms  (average mu = 0.069, current mu = 0.001) allocation failure scavenge might not succeed
[18304:0x3924b60]    41699 ms: Mark-sweep 1347.3 (1456.2) -> 1347.2 (1440.2) MB, 141.6 / 0.0 ms  (average mu = 0.035, current mu = 0.001) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x0f0dfe69e6e9 <JSObject>
    0: builtin exit frame: stringify(this=0x0f0dfe691a21 <Object map = 0x33024b5042a9>,0x26881e0826f1 <undefined>,0x26881e0826f1 <undefined>,0x379283b16cd1 <JSArray[7640]>,0x0f0dfe691a21 <Object map = 0x33024b5042a9>)

    1: arguments adaptor frame: 1->3
    2: stringify(aka stringify) [0x1097c01e5cb9] [/home/lionel/src/olpc/sugarizer-server/node_modules/express/lib/response.js:~1114] [pc=0x2e0...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa050 node::Abort() [node]
 2: 0x8fa09c  [node]
 3: 0xb0020e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb00444 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xef4952  [node]
 6: 0xef4a58 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xf00b32 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xf01464 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf02979 v8::internal::Heap::CollectAllAvailableGarbage(v8::internal::GarbageCollectionReason) [node]
10: 0xf0413e v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
11: 0xed3d1b v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
12: 0x1203f60 v8::internal::IncrementalStringBuilder::Extend() [node]
13: 0xfc8141 v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [node]
14: 0xfc859b v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
15: 0xfcd6ad v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
16: 0xfcabfa v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
17: 0xfcd6ad v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
18: 0xfcd316 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
19: 0xfce409 v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
20: 0xbd4d31 v8::internal::Builtin_JsonStringify(int, v8::internal::Object**, v8::internal::Isolate*) [node]
21: 0x2e091c8dbf7d 
Abandon (core dumped)
```

### PR DESCRIPTION
**Pull request by NikhilM98**
Fixes #208

@llaske can you please test this patch.

### CODE REVIEW

**Comment by llaske** [comment]
Nice, it works.

But seems that there is another issue. When I'm going to the Journal page (by clicking on the menu or on the Journal items count), the page is displayed but it hangs.

image

**Comment by NikhilM98** [comment]
The window is crashing because we're loading all the users at once in the Select2 select field. We've set the limit to 100000000 users in the getUsers query.
https://github.com/llaske/sugarizer-server/blob/6319475cb73cc2135d9cf3bcc08e677fd422e8b8/dashboard/controller/journal/util/index.js#L52-L75

**Comment by llaske** [comment]
Oooch if it's only to fill the select field, we could limit to 100 or 1000 users.
I guess it's possible to find users even if they are not present in the select field?

**Comment by NikhilM98** [comment]
@llaske I'm working on the fix. I've created a new API to search for users and will be using AJAX calls with Select2 to find users. Meanwhile, this PR targets a different problem and can be merged I guess.

**Comment by llaske** [comment]
Ok you're right, it's a different problem.
Thanks for this fix.

**Pull request merged**
