### PR TITLE
Update addAssignment.js

### PR DESCRIPTION
**Pull request by parteekcoder**
issue #365 

Now all the activities are shown not just 10

### CODE REVIEW

**Comment by parteekcoder** [comment]
@NikhilM98 @llaske I want to ask that we want this `icon` to be present inside the selection input or outside the selection input(now implemented)

image

**Comment by parteekcoder** [comment]
@NikhilM98 please give your suggestion , so that I get to know about the functionality required

**Comment by parteekcoder** [comment]
hey @NikhilM98 @llaske  Now it has as many journals as user can there no restriction like 10 , please review and I would appreciate the changes you prefer

**Comment by llaske** [comment]
> I want to ask that we want this icon to be present inside the selection input or outside the selection input(now implemented)

As mentioned in the issue, we want a popup similar to the one used to look for students in the Journal view. So with the icon inside the selection. Once selected the icon will be outside as today.

> Now it has as many journals as user can there no restriction like 10 

Hmmm. The idea was to make a smarter implementation, like a search field. Not to hardcode the limit.

**Pull request closed without merging**
