### PR TITLE
Fix Statistics page showing all users as inactive

### LINKED ISSUE #95: Statistics page shows all users as inactive
The **How many users actives during last month?** chart on the _statistics_ page shows that all users were inactive during last months even though they were!

inactive

Fixed here: #97

### PR DESCRIPTION
**Pull request by ahmedkrmn**
Fixes #95 

- All users were active during last month:
active 1

- Three users were active and two users weren't:
active 2

### CODE REVIEW

**Comment by llaske** [comment]
Very nice. Thanks a lot.
Could you check if there is no error on other stats?

**Comment by ahmedkrmn** [comment]
@llaske just went through the code of other statistic graphs. Everything is working as expected 👍

**Comment by ahmedkrmn** [comment]
@llaske #119

**Comment by Anshuman71** [comment]
> @llaske #119

thank you @ahmedkrmn for referencing the issue I have made new PR as we discussed

**Pull request merged**
