### PR TITLE
changes

### PR DESCRIPTION
**Pull request by tarunsinghal92**

### CODE REVIEW

**Comment by tarunsinghal92** [comment]
graph in dashboard added!

**Comment by llaske** [comment]
Do I need to do something special to run it ? I've got an issue here:

```
GET /api/v1/journal 200 7.377 ms - 337
/Users/lionel/src/olpc/sugarizer-server/dashboard/controller/graph.js:63
				labels.push(journals[i].user);
				                       ^

TypeError: Cannot read property 'user' of undefined
    at /Users/lionel/src/olpc/sugarizer-server/dashboard/controller/graph.js:63:28
    at Request._callback (/Users/lionel/src/olpc/sugarizer-server/dashboard/controller/dashboard.js:60:4)
    at Request.self.callback (/Users/lionel/src/olpc/sugarizer-server/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/lionel/src/olpc/sugarizer-server/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/lionel/src/olpc/sugarizer-server/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:286:16)
```

So I can see only the dashboard, not the other screens.

**Comment by tarunsinghal92** [comment]
Hi Lionel,

I have added a fix and sent the PR again. Let me know if that works well.

Thanks,

**Comment by tarunsinghal92** [comment]
ui changes

**Pull request merged**
