### PR TITLE
fix issue #111

### PR DESCRIPTION
**Pull request by ashish0910**
Now journal will show all users in select tag .

### CODE REVIEW

**Comment by ashish0910** [comment]
@NikhilM98 yes but there is a drawback there that if you want to search a user which is at 40th position then it might create a problem for the admin as he will not be able to find him in the list

**Comment by NikhilM98** [comment]
@ashish0910 I'm saying that Select2 has support for [Ajax requests](https://select2.org/advanced/default-adapters/ajax). With some modification in the backend, we'll be able to search for the users on the server side. Transferring data of thousands of users in a single request doesn't seem efficient.

**Comment by ashish0910** [comment]
@NikhilM98 yes that will be good . I will change it accordingly .

**Comment by ashish0910** [comment]
@llaske what are your views on this as adding a realtime search in select through AJAX might put some load as for example when admin types 'a' the query will start in background and start searching all the students with letter 'a' which will be in huge number and then when he press 's' then query will search for all users with 'as' in name which will again be huge number and process will go on like this . This is not looking very efficient .
I propose a search for name of the user using an input field as in user view and if the user do not exist a message will be shown saying no user found .

**Comment by NikhilM98** [comment]
@ashish0910 The search can be optimized.
- Set a limit for the number of users selected in one query.
- In the Select2 library, we're using, there's an option to set delay. You can set the delay to 250ms so as to avoid unnecessary queries.
- Optional: Set a minimum number of terms after which you start searching

**Comment by ashish0910** [comment]
@tarunsinghal92 can we have search similar to that in user views and show results if the user exists otherwise show user doesn't exist ?

**Pull request closed without merging**
