### PR TITLE
size column in journal view

### PR DESCRIPTION
**Pull request by ashish0910**
Earlier wrong field was used for showing size in journal view as mentioned by @llaske [here](https://github.com/llaske/sugarizer-server/pull/67#issuecomment-472199663)

Screenshot 2019-03-13 at 9 10 28 AM

### CODE REVIEW

**Comment by llaske** [comment]
Look like it don't works for all size. May be it's related to column size ?

image

Plus, miss a white space before "Bytes".

**Comment by ashish0910** [comment]
@llaske This should work now 

Screenshot 2019-03-13 at 1 37 16 PM

**Comment by llaske** [comment]
Nice. Could you localized strings like it was in [Sugarizer](https://github.com/llaske/sugarizer/blob/dev/lib/util.js#L543).

**Comment by ashish0910** [comment]
@llaske done in #104

**Pull request merged**
