### PR TITLE
Git pre-commit hook to run tests

### LINKED ISSUE #293: Adding GitHub Workflows/Actions/CI
Currently, the repository lacks GitHub Actions/workflows or GitHub CI. Some of the proposed additions are -
 
1. Merge conflict watcher that label PRs as `merge-conflict` if there's a merge conflict in it - can be done for both master and dev branches. 
2. Welcome first-time contributors (on new PR/issues) with a message. 
3. A [codeQL](https://codeql.github.com/docs/codeql-overview/about-codeql/) to check vulnerabilities across the repository. This can be configured for 2 cases - when a new PR is created, a CRON job that runs every Monday at 00:00 UTC, maybe? 
4. A workflow to close issues/PR that have not seen any activity in the last 45 days with prior 7-day notice. 
5. Issue templates for - bug reports, documentation updates, and feature request
6. Pull Request template.
7. Automated testing that installs the dependencies and runs `npm test` whenever a PR is made. 
7. Anything else that is important and I missed out. 

I'd love to hear suggestions/additions on this. 
CC @NikhilM98 @llaske

### PR DESCRIPTION
**Pull request by dhwaj1902**
fixes #293 

https://user-images.githubusercontent.com/57860123/159044570-577acacf-33eb-4af5-bdff-287ae4e3fb42.mp4

### CODE REVIEW

**Comment by dhwaj1902** [comment]
Once #311 gets resolved, I can add the linting also in ``pre-commit``.

**Comment by NikhilM98** [comment]
You're using a deprecated library in this PR which was last updated 5 years ago (https://www.npmjs.com/package/pre-commit).
It's better to use a more actively maintained and stable alternative.

**Comment by dhwaj1902** [comment]
Can I use [husky](https://www.npmjs.com/package/husky) for ``pre-commit``

**Comment by NikhilM98** [comment]
Yeah, husky seems pretty good!

**Comment by dhwaj1902** [comment]
@NikhilM98 please check!

**Comment by llaske** [comment]
Thanks.
Merged in dev branch here: https://github.com/llaske/sugarizer-server/commit/cc73940cf9f6680d586cd1ce49d9ee06f50e88f6

**Pull request closed without merging**
